SaaShup/netbox-docker-agent

- Dockerfile
- README.md
- config.js
- flows.json
- package.json
replace node-red default package with netbox-docker-agent
fix config files in data
fix no response on unix socket issue on host registration
> Change default package

- flows.json
- package.json
add none value as operation
add network and image prune daily
> add none cmd and prune net/image

- flows.json
- package.json
fix container creation if single env
> fix single env

- README.md
- flows.json
- package.json
:sparkles: Add Metrics path [#5 ]
> Implement metrics

- LICENSE
:page_facing_up: Update license to BSD-3
> :page_facing_up: update license to BSD-3

- README.md
- flows.json
- index.html
- package.json
- Add Network state handling https://github.com/SaaShup/netbox-docker-agent/issues/10
- add ui screenshot in readme
- fix kernel label typo in ui
> Add Network state

- flows.json
- package.json
add imageId 32 bytes in version as a temp fix for duplicate none image
> image duplicate fix

- openapi.yml
- package.json
https://github.com/SaaShup/netbox-docker-agent/issues/15
> add openapi

- flows.json
- package.json
add ui toggler to disable/enable ui
> UI toggler

- flows.json
- package.json
change to none if null driver network
> fix null network driver

- flows.json
- package.json
add journal on container cmd
fix ' in recreate
> add journal container

- flows.json
- package.json
- :bug: Fix image parsing with the right version and name
> :bug: Fix image parsing with the right version and name

- flows.json
- package.json
fix package version on start
removed unused nodes
> fix package on start

- flows.json
- package.json
update host and add journal on agent restart
> update host and add journal on agent restart

- config.js
- package.json
- public/openapi.json
- public/openapi.yml
- tests/functional/doc.test.js
- tests/functional/inc.js
High level proposal for testing based on openapi...
> proposal to simplify tests

- Dockerfile
- config.js
- flows.json
- package.json
- public/index.html
- registries.js
:sparkles:  Implement registry based on netbox-docker-plugin model
:wastebasket: Remove registry.js since it's not needed anymore
> :sparkles: Implement registry

- config.js
- flows.json
- package.json
> Fix image add and delete

- config.js
- flows.json
- package.json
Implement Registry init based on [#50 ]
this depends on changing inside the netbox docker plugin to put https://github.com/SaaShup/netbox-docker-plugin/blob/main/netbox_docker_plugin/api/serializers.py#L182 on false.
> :sparkles: Add registry init

- flows.json
- package-lock.json
- package.json
https://github.com/SaaShup/netbox-docker-agent/issues/57 add journal 
but couldnt resist to clean up :(
> add journal 

- config.js
- flows.json
- package.json
- Allow env(NETBOX_URL) to override url provided by netbox
> :sparkles: add netbox_url config

- package.json
- tests/functional/metrics.test.js
- tests/functional/root.test.js
> add metrics and root test

- config.js
- flows.json
- package.json
- :bug: Fix metrics on no socket connection
> :bug: fix metrics on daemon.socket failure

- config.js
- flows.json
- package-lock.json
- package.json
adding action on image post request : 
- adding "polling image" upon event received on image journal
- adding pulled success or failed based on image result in the journal
adding action on image delete request : 
- adding image delete on host journal
> :sparkles: add journal image actions

- config.js
- flows.json
- package-lock.json
- package.json
implement into the agent the feature from https://github.com/SaaShup/netbox-docker-plugin/pull/109
> :sparkles: add digest image into netbox

- config.js
- flows.json
- package-lock.json
- package.json
:sparkles: remove image version limit to 12
:sparkles: add journal on container creation
> :sparkles: remove version limit to 12

- config.js
- flows.json
- package-lock.json
- package.json
- public/index.html
https://github.com/SaaShup/netbox-docker-agent/issues/83
> :bug: Fix UI restart policy

- flows.json
- package-lock.json
- package.json
- public/index.html
- public/openapi.json
- public/openapi.yml
> :sparkles: Add exec command

- flows.json
- package-lock.json
- package.json
related to https://github.com/SaaShup/netbox-docker-agent/issues/23
- logs in ui added
- metrics already present
- stdout logs every 5 secondes
> Add a log when Docker socket is not writable

- flows.json
- package-lock.json
- package.json
:ambulance: fix reponse if container logs are empty
> :ambulance: fix reponse if container logs are empty

- flows.json
- package-lock.json
- package.json
Some people have some "lazy" containers that can take time to be stopped.
Adding the wait api call after the docker stop during the recreation to avoid stopping issues or delayes.
> :bulb: adding wait on stop during recreation

- flows.json
- package-lock.json
- package.json
- public/index.html
In the UI we do not have the operation implemented.
This PR add the operation except the recreate as this one is more complex and would require a specific PR.
Some adjustments have been made in case agent has no netbox configured : to avoid sending message to nowhere in the call back maechnism.
> :sparkles: Add UI put action button

- flows.json
- package-lock.json
- package.json
When a recreate fails the container may be in an invalid status in netbox docker plugin.
It is hard to reproduce but cases have happens.
With this PR we refresh the container statuses and information if : 
- the new container can not be created
- the new container can not be started
> :sparkle: Callback to netbox docker container on recreate error

- flows.json
- package-lock.json
- package.json
Adding the wait on stop when the plugin has requested a stop container.
It was only implemented on the container recreate but it looks it is also needed for stopping a container as it may take quite a bit of time.
> :zap: add wait on stop (added to more but useless)

- flows.json
- package-lock.json
- package.json
> :sparkles: Add stderr on exec command return

- flows.json
- package-lock.json
- package.json
fix https://github.com/SaaShup/netbox-docker-agent/issues/129
> :wrench: add check on imageId when pulling image

- flows.json
- package-lock.json
- package.json
> :bug: Fix registries index creation

- flows.json
- package-lock.json
- package.json
- public/index.html
- Add pulling button in UI : 
- Add a check for netbox callback if settings is existing on pulling api
- Add better error message on pull failure
> :sparkles: add force pull in ui

- flows.json
- package-lock.json
- package.json
- public/index.html
this PR is the first step to add recreate in the UI.
It will not be self sufficient to add the feature as extra changes will be required that may have more impact.
> 1 8 0 recreate and more

- flows.json
- package.json
Fix https://github.com/SaaShup/netbox-docker-plugin/issues/179
> :sparkles: Activate Host network mode

- Dockerfile
- flows.json
- lib/docker-exec-websocket.js
- package-lock.json
- package.json
- public/doc.html
- public/index.html
- public/js/docker-exec-client.js
- public/openapi.yml
- settings.js
- settings_dev.js
Add the possibility to open a terminal on a running container.
Like exec but in the browser. Run because websocket exits. Please test :-)
Need to do before merge (or not):
> :sparkles: Open terminal with exec command on a Container

- package-lock.json
- package.json
- public/index.html
:lipstick: add registry check in ui
:lipstick: add syslog config in ui
> UI update to add registry improvement and syslog configuration
